# Generated by Django 3.1.4 on 2020-12-20 08:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('directions', models.CharField(max_length=400)),
                ('link', models.CharField(max_length=64)),
                ('ingredients_all', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None)),
                ('ingredients_needed', models.ManyToManyField(related_name='needed', to='recipes.Ingredient')),
                ('ingredients_used', models.ManyToManyField(related_name='used', to='recipes.Ingredient')),
            ],
        ),
    ]
