# Generated by Django 3.1.4 on 2020-12-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients_all',
            new_name='ing_all',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients_needed',
            new_name='needed',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients_used',
            new_name='used',
        ),
    ]
