# Generated by Django 3.1.4 on 2020-12-20 08:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20201220_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='needed',
        ),
        migrations.AddField(
            model_name='recipe',
            name='needed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=[''], size=None),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='used',
        ),
        migrations.AddField(
            model_name='recipe',
            name='used',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=[''], size=None),
        ),
    ]
