# Generated by Django 3.1.4 on 2020-12-20 08:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20201220_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='needed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='used',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=list, size=None),
        ),
    ]
